title: Modern Robotics Notes
description: Notes taken for the Coursera MOOC 'Modern Robotics'
show_downloads: false
google_analytics: false
theme: jekyll-theme-cayman
mathjax: true
markdown: kramdown
